[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200
via_ir = false

remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@aragon/osx-commons-contracts/=lib/ve-governance/lib/osx-commons/contracts/",
    "@escrow/=lib/ve-governance/src/escrow/",
    "@voting/=lib/ve-governance/src/voting/",
    "@clock/=lib/ve-governance/src/clock/",
    "@curve/=lib/ve-governance/src/curve/",
    "@queue/=lib/ve-governance/src/queue/",
    "@lock/=lib/ve-governance/src/lock/",
    "@libs/=lib/ve-governance/src/libs/",
    "@delegation/=lib/ve-governance/src/delegation/",
    "forge-std/=lib/forge-std/src/"
]

[profile.default.fuzz]
runs = 256

[profile.ci]
fuzz_runs = 10000

[rpc_endpoints]
fushuma = "https://rpc.fushuma.com"
fushuma_testnet = "${FUSHUMA_TESTNET_RPC_URL}"

[etherscan]
fushuma = { key = "${ETHERSCAN_API_KEY}", url = "https://fumascan.com/api" }
